--------------------------------------------------------
--  File created - Wednesday-September-02-2020   
--------------------------------------------------------
DROP TABLE "ECOSFERA"."CARACTERISTICAS" cascade constraints;
DROP TABLE "ECOSFERA"."DEPARTAMENTOS" cascade constraints;
DROP TABLE "ECOSFERA"."DETALLES" cascade constraints;
DROP TABLE "ECOSFERA"."ESTADOS" cascade constraints;
DROP TABLE "ECOSFERA"."IMAGENES" cascade constraints;
DROP TABLE "ECOSFERA"."ITEMSSELECCIONES" cascade constraints;
DROP TABLE "ECOSFERA"."LOCALIDADES" cascade constraints;
DROP TABLE "ECOSFERA"."OBSERVACIONES" cascade constraints;
DROP TABLE "ECOSFERA"."PERFILES" cascade constraints;
DROP TABLE "ECOSFERA"."PERFILES_PERMISOS" cascade constraints;
DROP TABLE "ECOSFERA"."PERMISOS" cascade constraints;
DROP TABLE "ECOSFERA"."REVISIONES" cascade constraints;
DROP TABLE "ECOSFERA"."TIPOSDOCUMENTOS" cascade constraints;
DROP TABLE "ECOSFERA"."TIPOSOBSERVACIONES" cascade constraints;
DROP TABLE "ECOSFERA"."USUARIOS" cascade constraints;
DROP TABLE "ECOSFERA"."USUARIOS_PERFILES" cascade constraints;
DROP TABLE "ECOSFERA"."ZONAS" cascade constraints;
DROP SEQUENCE "ECOSFERA"."SEQ_ID_CARACTERISTICA";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_DEPARTAMENTO";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_DETALLE";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_ESTADO";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_IMAGEN";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_ITEMSELECCION";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_LOCALIDAD";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_OBSERVACION";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_PERFIL";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_PERMISO";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_REVISION";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_TIPODOCUMENTO";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_TIPOOBSERVACION";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_USUARIO";
DROP SEQUENCE "ECOSFERA"."SEQ_ID_ZONA";
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_CARACTERISTICA
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_CARACTERISTICA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_DEPARTAMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_DEPARTAMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_DETALLE
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_DETALLE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_ESTADO
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_ESTADO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_IMAGEN
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_IMAGEN"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_ITEMSELECCION
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_ITEMSELECCION"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_LOCALIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_LOCALIDAD"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_OBSERVACION
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_OBSERVACION"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_PERFIL
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_PERFIL"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_PERMISO
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_PERMISO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 42 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_REVISION
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_REVISION"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_TIPODOCUMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_TIPODOCUMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_TIPOOBSERVACION
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_TIPOOBSERVACION"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_USUARIO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_ZONA
--------------------------------------------------------

   CREATE SEQUENCE  "ECOSFERA"."SEQ_ID_ZONA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CARACTERISTICAS
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."CARACTERISTICAS" 
   (	"ID_CARACTERISTICA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(250 BYTE), 
	"TIPODATO" VARCHAR2(10 BYTE), 
	"ID_TIPOOBSERVACION" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTOS
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."DEPARTAMENTOS" 
   (	"ID_DEPARTAMENTO" NUMBER(*,0), 
	"ID_ZONA" NUMBER(*,0), 
	"CODIGO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLES
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."DETALLES" 
   (	"ID_DETALLE" NUMBER(*,0), 
	"ID_OBSERVACION" NUMBER(*,0), 
	"ID_CARACTERISTICA" NUMBER(*,0), 
	"ID_ITEMSELECCION" NUMBER(*,0), 
	"VAL_NUMERICO" NUMBER(*,0), 
	"VAL_TEXTO" VARCHAR2(100 BYTE), 
	"VAL_FECHA" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTADOS
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."ESTADOS" 
   (	"ID_ESTADO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"PER_LOGIN" CHAR(1 BYTE), 
	"PER_REGISTRO" CHAR(1 BYTE), 
	"ELIM_LOGICA" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMAGENES
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."IMAGENES" 
   (	"ID_IMAGEN" NUMBER(*,0), 
	"ID_OBSERVACION" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"TAG" VARCHAR2(500 BYTE), 
	"IMAGEN" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGEN") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ITEMSSELECCIONES
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."ITEMSSELECCIONES" 
   (	"ID_ITEMSELECCION" NUMBER(*,0), 
	"ID_CARACTERISTICA" NUMBER(*,0), 
	"CODIGO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCALIDADES
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."LOCALIDADES" 
   (	"ID_LOCALIDAD" NUMBER(*,0), 
	"ID_DEPARTAMENTO" NUMBER(*,0), 
	"CODIGO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OBSERVACIONES
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."OBSERVACIONES" 
   (	"ID_OBSERVACION" NUMBER(*,0), 
	"FECHA" DATE, 
	"DESCRIPCION" VARCHAR2(250 BYTE), 
	"GEOLOCALIZACION" VARCHAR2(100 BYTE), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_LOCALIDAD" NUMBER(*,0), 
	"ID_TIPOOBSERVACION" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFILES
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."PERFILES" 
   (	"ID_PERFIL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFILES_PERMISOS
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."PERFILES_PERMISOS" 
   (	"ID_PERFIL" NUMBER(38,0), 
	"ID_PERMISO" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERMISOS
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."PERMISOS" 
   (	"ID_PERMISO" NUMBER(*,0), 
	"FUNCIONALIDAD" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REVISIONES
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."REVISIONES" 
   (	"ID_REVISION" NUMBER(*,0), 
	"COMENTARIOS" VARCHAR2(250 BYTE), 
	"FECHA" DATE, 
	"FIABILIDAD" VARCHAR2(50 CHAR), 
	"ID_OBSERVACION" NUMBER(38,0), 
	"ID_USUARIO" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPOSDOCUMENTOS
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."TIPOSDOCUMENTOS" 
   (	"ID_TIPODOCUMENTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ABREVIATURA" VARCHAR2(5 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPOSOBSERVACIONES
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."TIPOSOBSERVACIONES" 
   (	"ID_TIPOOBSERVACION" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(250 BYTE), 
	"TEL_EMERGENCIA" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."USUARIOS" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"USUARIO" VARCHAR2(30 BYTE), 
	"ID_TIPODOCUMENTO" NUMBER(*,0), 
	"DOCUMENTO" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"MAIL" VARCHAR2(30 BYTE), 
	"PASSWRD" VARCHAR2(30 BYTE), 
	"ID_ESTADO" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS_PERFILES
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."USUARIOS_PERFILES" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"ID_PERFIL" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZONAS
--------------------------------------------------------

  CREATE TABLE "ECOSFERA"."ZONAS" 
   (	"ID_ZONA" NUMBER(*,0), 
	"CODIGO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CARACTERISTICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_CARACTERISTICA" ON "ECOSFERA"."CARACTERISTICAS" ("ID_CARACTERISTICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DEPARTAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_DEPARTAMENTO" ON "ECOSFERA"."DEPARTAMENTOS" ("ID_DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DETALLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_DETALLE" ON "ECOSFERA"."DETALLES" ("ID_DETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ESTADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_ESTADO" ON "ECOSFERA"."ESTADOS" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_IMAGEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_IMAGEN" ON "ECOSFERA"."IMAGENES" ("ID_IMAGEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ITEMSELECCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_ITEMSELECCION" ON "ECOSFERA"."ITEMSSELECCIONES" ("ID_ITEMSELECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LOCALIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_LOCALIDAD" ON "ECOSFERA"."LOCALIDADES" ("ID_LOCALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_OBSERVACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_OBSERVACION" ON "ECOSFERA"."OBSERVACIONES" ("ID_OBSERVACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PERFIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_PERFIL" ON "ECOSFERA"."PERFILES" ("ID_PERFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PERFILES_PERMISOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_PERFILES_PERMISOS" ON "ECOSFERA"."PERFILES_PERMISOS" ("ID_PERFIL", "ID_PERMISO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PERMISO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_PERMISO" ON "ECOSFERA"."PERMISOS" ("ID_PERMISO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_REVISION
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_REVISION" ON "ECOSFERA"."REVISIONES" ("ID_REVISION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIPODOCUMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_TIPODOCUMENTO" ON "ECOSFERA"."TIPOSDOCUMENTOS" ("ID_TIPODOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIPOOBSERVACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_TIPOOBSERVACION" ON "ECOSFERA"."TIPOSOBSERVACIONES" ("ID_TIPOOBSERVACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_USUARIO" ON "ECOSFERA"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIO_PERFIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_USUARIO_PERFIL" ON "ECOSFERA"."USUARIOS_PERFILES" ("ID_USUARIO", "ID_PERFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ZONA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."PK_ZONA" ON "ECOSFERA"."ZONAS" ("ID_ZONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_DEPARTAMENTO_NOMBRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_DEPARTAMENTO_NOMBRE" ON "ECOSFERA"."DEPARTAMENTOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_DEPARTAMENTO_ZONA_CODIGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_DEPARTAMENTO_ZONA_CODIGO" ON "ECOSFERA"."DEPARTAMENTOS" ("ID_ZONA", "CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ESTA_NOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_ESTA_NOM" ON "ECOSFERA"."ESTADOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_LOCALIDAD_DEPTO_COD
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_LOCALIDAD_DEPTO_COD" ON "ECOSFERA"."LOCALIDADES" ("ID_DEPARTAMENTO", "CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_LOCALIDAD_NOMBRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_LOCALIDAD_NOMBRE" ON "ECOSFERA"."LOCALIDADES" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_PERF_NOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_PERF_NOM" ON "ECOSFERA"."PERFILES" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_PERM_FUN
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_PERM_FUN" ON "ECOSFERA"."PERMISOS" ("FUNCIONALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_TIPDOC_ABRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_TIPDOC_ABRE" ON "ECOSFERA"."TIPOSDOCUMENTOS" ("ABREVIATURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_TIPDOC_NOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_TIPDOC_NOM" ON "ECOSFERA"."TIPOSDOCUMENTOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_TIPOOBSERVACION_NOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_TIPOOBSERVACION_NOM" ON "ECOSFERA"."TIPOSOBSERVACIONES" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USUARIO_MAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_USUARIO_MAIL" ON "ECOSFERA"."USUARIOS" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USUARIO_TDOC_DOC
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_USUARIO_TDOC_DOC" ON "ECOSFERA"."USUARIOS" ("ID_TIPODOCUMENTO", "DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USUARIO_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_USUARIO_USUARIO" ON "ECOSFERA"."USUARIOS" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ZONA_CODIGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_ZONA_CODIGO" ON "ECOSFERA"."ZONAS" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ZONA_NOMBRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOSFERA"."UK_ZONA_NOMBRE" ON "ECOSFERA"."ZONAS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CARACTERISTICAS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."CARACTERISTICAS" ADD CONSTRAINT "PK_CARACTERISTICA" PRIMARY KEY ("ID_CARACTERISTICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."CARACTERISTICAS" MODIFY ("ID_CARACTERISTICA" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."CARACTERISTICAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."CARACTERISTICAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."CARACTERISTICAS" MODIFY ("TIPODATO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."CARACTERISTICAS" MODIFY ("ID_TIPOOBSERVACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTOS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."DEPARTAMENTOS" ADD CONSTRAINT "PK_DEPARTAMENTO" PRIMARY KEY ("ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."DEPARTAMENTOS" MODIFY ("ID_DEPARTAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."DEPARTAMENTOS" MODIFY ("ID_ZONA" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."DEPARTAMENTOS" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."DEPARTAMENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."DEPARTAMENTOS" ADD CONSTRAINT "UK_DEPARTAMENTO_NOMBRE" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."DEPARTAMENTOS" ADD CONSTRAINT "UK_DEPARTAMENTO_ZONA_CODIGO" UNIQUE ("ID_ZONA", "CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."DETALLES" ADD CONSTRAINT "PK_DETALLE" PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."DETALLES" MODIFY ("ID_DETALLE" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."DETALLES" MODIFY ("ID_OBSERVACION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."DETALLES" MODIFY ("ID_CARACTERISTICA" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."DETALLES" MODIFY ("ID_ITEMSELECCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADOS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."ESTADOS" ADD CONSTRAINT "CHE_ESTADO_ELIM_LOGICA" CHECK ( ELIM_LOGICA IN ('S','N')) ENABLE;
 
  ALTER TABLE "ECOSFERA"."ESTADOS" ADD CONSTRAINT "CHE_ESTADO_PER_LOGIN" CHECK ( PER_LOGIN IN ('S','N')) ENABLE;
 
  ALTER TABLE "ECOSFERA"."ESTADOS" ADD CONSTRAINT "CHE_ESTADO_PER_REGISTRO" CHECK ( PER_REGISTRO IN ('S','N')) ENABLE;
 
  ALTER TABLE "ECOSFERA"."ESTADOS" ADD CONSTRAINT "PK_ESTADO" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."ESTADOS" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."ESTADOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."ESTADOS" MODIFY ("PER_LOGIN" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."ESTADOS" MODIFY ("PER_REGISTRO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."ESTADOS" MODIFY ("ELIM_LOGICA" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."ESTADOS" ADD CONSTRAINT "UK_ESTA_NOM" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IMAGENES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."IMAGENES" ADD CONSTRAINT "PK_IMAGEN" PRIMARY KEY ("ID_IMAGEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."IMAGENES" MODIFY ("ID_IMAGEN" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."IMAGENES" MODIFY ("ID_OBSERVACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEMSSELECCIONES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."ITEMSSELECCIONES" ADD CONSTRAINT "PK_ITEMSELECCION" PRIMARY KEY ("ID_ITEMSELECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."ITEMSSELECCIONES" MODIFY ("ID_ITEMSELECCION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."ITEMSSELECCIONES" MODIFY ("ID_CARACTERISTICA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCALIDADES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."LOCALIDADES" ADD CONSTRAINT "PK_LOCALIDAD" PRIMARY KEY ("ID_LOCALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."LOCALIDADES" MODIFY ("ID_LOCALIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."LOCALIDADES" MODIFY ("ID_DEPARTAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."LOCALIDADES" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."LOCALIDADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."LOCALIDADES" ADD CONSTRAINT "UK_LOCALIDAD_DEPTO_COD" UNIQUE ("ID_DEPARTAMENTO", "CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."LOCALIDADES" ADD CONSTRAINT "UK_LOCALIDAD_NOMBRE" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBSERVACIONES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."OBSERVACIONES" ADD CONSTRAINT "PK_OBSERVACION" PRIMARY KEY ("ID_OBSERVACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."OBSERVACIONES" MODIFY ("ID_OBSERVACION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."OBSERVACIONES" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."OBSERVACIONES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."OBSERVACIONES" MODIFY ("GEOLOCALIZACION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."OBSERVACIONES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."OBSERVACIONES" MODIFY ("ID_LOCALIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."OBSERVACIONES" MODIFY ("ID_TIPOOBSERVACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERFILES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."PERFILES" ADD CONSTRAINT "PK_PERFIL" PRIMARY KEY ("ID_PERFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."PERFILES" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."PERFILES" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."PERFILES" ADD CONSTRAINT "UK_PERF_NOM" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERFILES_PERMISOS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."PERFILES_PERMISOS" ADD CONSTRAINT "PK_PERFILES_PERMISOS" PRIMARY KEY ("ID_PERFIL", "ID_PERMISO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."PERFILES_PERMISOS" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."PERFILES_PERMISOS" MODIFY ("ID_PERMISO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERMISOS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."PERMISOS" ADD CONSTRAINT "PK_PERMISO" PRIMARY KEY ("ID_PERMISO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."PERMISOS" MODIFY ("ID_PERMISO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."PERMISOS" MODIFY ("FUNCIONALIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."PERMISOS" ADD CONSTRAINT "UK_PERM_FUN" UNIQUE ("FUNCIONALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVISIONES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."REVISIONES" ADD CONSTRAINT "PK_REVISION" PRIMARY KEY ("ID_REVISION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."REVISIONES" MODIFY ("ID_REVISION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."REVISIONES" MODIFY ("COMENTARIOS" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."REVISIONES" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."REVISIONES" MODIFY ("FIABILIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."REVISIONES" MODIFY ("ID_OBSERVACION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."REVISIONES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPOSDOCUMENTOS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."TIPOSDOCUMENTOS" ADD CONSTRAINT "PK_TIPODOCUMENTO" PRIMARY KEY ("ID_TIPODOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."TIPOSDOCUMENTOS" MODIFY ("ID_TIPODOCUMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."TIPOSDOCUMENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."TIPOSDOCUMENTOS" MODIFY ("ABREVIATURA" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."TIPOSDOCUMENTOS" ADD CONSTRAINT "UK_TIPDOC_ABRE" UNIQUE ("ABREVIATURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."TIPOSDOCUMENTOS" ADD CONSTRAINT "UK_TIPDOC_NOM" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOSOBSERVACIONES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."TIPOSOBSERVACIONES" ADD CONSTRAINT "PK_TIPOOBSERVACION" PRIMARY KEY ("ID_TIPOOBSERVACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."TIPOSOBSERVACIONES" MODIFY ("ID_TIPOOBSERVACION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."TIPOSOBSERVACIONES" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."TIPOSOBSERVACIONES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."TIPOSOBSERVACIONES" MODIFY ("TEL_EMERGENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."TIPOSOBSERVACIONES" ADD CONSTRAINT "UK_TIPOOBSERVACION_NOM" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."USUARIOS" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS" MODIFY ("USUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS" MODIFY ("ID_TIPODOCUMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS" MODIFY ("DOCUMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS" MODIFY ("APELLIDO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS" MODIFY ("DIRECCION" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS" MODIFY ("MAIL" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS" MODIFY ("PASSWRD" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS" ADD CONSTRAINT "UK_USUARIO_MAIL" UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."USUARIOS" ADD CONSTRAINT "UK_USUARIO_TDOC_DOC" UNIQUE ("ID_TIPODOCUMENTO", "DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."USUARIOS" ADD CONSTRAINT "UK_USUARIO_USUARIO" UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS_PERFILES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."USUARIOS_PERFILES" ADD CONSTRAINT "PK_USUARIO_PERFIL" PRIMARY KEY ("ID_USUARIO", "ID_PERFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."USUARIOS_PERFILES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."USUARIOS_PERFILES" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZONAS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."ZONAS" ADD CONSTRAINT "PK_ZONA" PRIMARY KEY ("ID_ZONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."ZONAS" MODIFY ("ID_ZONA" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."ZONAS" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."ZONAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ECOSFERA"."ZONAS" ADD CONSTRAINT "UK_ZONA_CODIGO" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ECOSFERA"."ZONAS" ADD CONSTRAINT "UK_ZONA_NOMBRE" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CARACTERISTICAS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."CARACTERISTICAS" ADD CONSTRAINT "FK_CARACTERISTICA_TPOOBS" FOREIGN KEY ("ID_TIPOOBSERVACION")
	  REFERENCES "ECOSFERA"."TIPOSOBSERVACIONES" ("ID_TIPOOBSERVACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTAMENTOS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."DEPARTAMENTOS" ADD CONSTRAINT "FK_DEPARTAMENTO_ZONA" FOREIGN KEY ("ID_ZONA")
	  REFERENCES "ECOSFERA"."ZONAS" ("ID_ZONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."DETALLES" ADD CONSTRAINT "FK_DETALLE_CARACT" FOREIGN KEY ("ID_CARACTERISTICA")
	  REFERENCES "ECOSFERA"."CARACTERISTICAS" ("ID_CARACTERISTICA") ENABLE;
 
  ALTER TABLE "ECOSFERA"."DETALLES" ADD CONSTRAINT "FK_DETALLE_ITEMSEL" FOREIGN KEY ("ID_ITEMSELECCION")
	  REFERENCES "ECOSFERA"."ITEMSSELECCIONES" ("ID_ITEMSELECCION") ENABLE;
 
  ALTER TABLE "ECOSFERA"."DETALLES" ADD CONSTRAINT "FK_DETALLE_OBSERV" FOREIGN KEY ("ID_OBSERVACION")
	  REFERENCES "ECOSFERA"."OBSERVACIONES" ("ID_OBSERVACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IMAGENES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."IMAGENES" ADD CONSTRAINT "FK_IMAGEN_OBS" FOREIGN KEY ("ID_OBSERVACION")
	  REFERENCES "ECOSFERA"."OBSERVACIONES" ("ID_OBSERVACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEMSSELECCIONES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."ITEMSSELECCIONES" ADD CONSTRAINT "FK_ITEMSELECCION_CARACT" FOREIGN KEY ("ID_CARACTERISTICA")
	  REFERENCES "ECOSFERA"."CARACTERISTICAS" ("ID_CARACTERISTICA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCALIDADES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."LOCALIDADES" ADD CONSTRAINT "FK_LOCALIDAD_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "ECOSFERA"."DEPARTAMENTOS" ("ID_DEPARTAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OBSERVACIONES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."OBSERVACIONES" ADD CONSTRAINT "FK_OBSERVACION_LOCALIDAD" FOREIGN KEY ("ID_LOCALIDAD")
	  REFERENCES "ECOSFERA"."LOCALIDADES" ("ID_LOCALIDAD") ENABLE;
 
  ALTER TABLE "ECOSFERA"."OBSERVACIONES" ADD CONSTRAINT "FK_OBSERVACION_TPOOBS" FOREIGN KEY ("ID_TIPOOBSERVACION")
	  REFERENCES "ECOSFERA"."TIPOSOBSERVACIONES" ("ID_TIPOOBSERVACION") ENABLE;
 
  ALTER TABLE "ECOSFERA"."OBSERVACIONES" ADD CONSTRAINT "FK_OBSERVACION_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ECOSFERA"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFILES_PERMISOS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."PERFILES_PERMISOS" ADD CONSTRAINT "FK_PERFPERM_PERF" FOREIGN KEY ("ID_PERFIL")
	  REFERENCES "ECOSFERA"."PERFILES" ("ID_PERFIL") ENABLE;
 
  ALTER TABLE "ECOSFERA"."PERFILES_PERMISOS" ADD CONSTRAINT "FK_PERFPERM_PERM" FOREIGN KEY ("ID_PERMISO")
	  REFERENCES "ECOSFERA"."PERMISOS" ("ID_PERMISO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVISIONES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."REVISIONES" ADD CONSTRAINT "FK_REVISION_OBSERV" FOREIGN KEY ("ID_OBSERVACION")
	  REFERENCES "ECOSFERA"."OBSERVACIONES" ("ID_OBSERVACION") ENABLE;
 
  ALTER TABLE "ECOSFERA"."REVISIONES" ADD CONSTRAINT "FK_REVISION_USUARI" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ECOSFERA"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."USUARIOS" ADD CONSTRAINT "FK_USUARIO_EST" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "ECOSFERA"."ESTADOS" ("ID_ESTADO") ENABLE;
 
  ALTER TABLE "ECOSFERA"."USUARIOS" ADD CONSTRAINT "FK_USUARIO_TDOC" FOREIGN KEY ("ID_TIPODOCUMENTO")
	  REFERENCES "ECOSFERA"."TIPOSDOCUMENTOS" ("ID_TIPODOCUMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS_PERFILES
--------------------------------------------------------

  ALTER TABLE "ECOSFERA"."USUARIOS_PERFILES" ADD CONSTRAINT "FK_USUARIO_PERFIL_PERFIL" FOREIGN KEY ("ID_PERFIL")
	  REFERENCES "ECOSFERA"."PERFILES" ("ID_PERFIL") ENABLE;
 
  ALTER TABLE "ECOSFERA"."USUARIOS_PERFILES" ADD CONSTRAINT "FK_USUARIO_PERFIL_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ECOSFERA"."USUARIOS" ("ID_USUARIO") ENABLE;