DROP TABLE D_ZONA;
CREATE TABLE D_ZONA(SK_ZONA,ZONA_PK,NOMBRE,
CONSTRAINT SK_ZONA PRIMARY KEY (SK_ZONA))
AS
SELECT ID_ZONA, CODIGO, NOMBRE FROM Ecosfera_MK2.ZONAS;

DROP TABLE D_DEPARTAMENTO;
CREATE TABLE D_DEPARTAMENTO(SK_DEPARTAMENTO, DEPARTAMENTO_PK, NOMBRE,
CONSTRAINT SK_DEPARTAMENTO PRIMARY KEY(SK_DEPARTAMENTO))
AS
SELECT ID_DEPARTAMENTO, CODIGO, NOMBRE FROM ECOSFERA_MK2.DEPARTAMENTOS;

DROP TABLE D_LOCALIDAD;
CREATE TABLE D_LOCALIDAD(SK_LOCALIDAD, LOCALIDAD_PK, NOMBRE,
CONSTRAINT SK_LOCALIDAD PRIMARY KEY(SK_LOCALIDAD))
AS 
SELECT ID_LOCALIDAD, CODIGO, NOMBRE FROM ECOSFERA_MK2.LOCALIDADES;

DROP TABLE D_TIPO_OBSERVACION;
CREATE TABLE D_TIPO_OBSERVACION(SK_TIPO_OBSERVACION, NOMBRE, DESCRIPCION,
CONSTRAINT SK_TIPO_OBSERVACION PRIMARY KEY(SK_TIPO_OBSERVACION))
AS 
SELECT ID_TIPOOBSERVACION, NOMBRE, DESCRIPCION FROM ECOSFERA_MK2.TIPOSOBSERVACIONES;

DROP TABLE D_REVISION;
CREATE TABLE D_REVISION(SK_REVISION, FECHA, FIABILIDAD,
CONSTRAINT SK_REVISION PRIMARY KEY(SK_REVISION))
AS 
SELECT ID_REVISION, FECHA, FIABILIDAD FROM ECOSFERA_MK2.REVISIONES;

DROP TABLE D_USUARIO;
CREATE TABLE D_USUARIO(SK_USUARIO, USUARIO,
CONSTRAINT SK_USUARIO PRIMARY KEY(SK_USUARIO))
AS
SELECT ID_USUARIO, USUARIO FROM ECOSFERA_MK2.USUARIOS;

DROP TABLE H_OBSERVACION;
CREATE TABLE H_OBSERVACION(SK_OBSERVACION, SK_ZONA, SK_LOCALIDAD, SK_DEPARTAMENTO, SK_REVISION, SK_USUARIO, SK_TIPO_OBSERVACION, FECHA,
CONSTRAINT SK_H_OBSERVACION PRIMARY KEY(SK_OBSERVACION,SK_ZONA,SK_LOCALIDAD,SK_DEPARTAMENTO,SK_USUARIO,SK_TIPO_OBSERVACION))
AS   
SELECT O.ID_OBSERVACION, Z.ID_ZONA, D.ID_DEPARTAMENTO, L.ID_LOCALIDAD, R.ID_REVISION, U.ID_USUARIO, T.ID_TIPOOBSERVACION, O.FECHA FROM ECOSFERA_MK2.OBSERVACIONES O 
JOIN ECOSFERA_MK2.LOCALIDADES L ON O.ID_LOCALIDAD = L.ID_LOCALIDAD JOIN ECOSFERA_MK2.DEPARTAMENTOS D 
ON L.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO JOIN ECOSFERA_MK2.ZONAS Z ON D.ID_ZONA = Z.ID_ZONA LEFT JOIN ECOSFERA_MK2.REVISIONES R 
ON O.ID_OBSERVACION = R.ID_OBSERVACION JOIN ECOSFERA_MK2.USUARIOS U  ON O.ID_USUARIO = U.ID_USUARIO JOIN ECOSFERA_MK2.TIPOSOBSERVACIONES T 
ON O.ID_TIPOOBSERVACION = T.ID_TIPOOBSERVACION;
  
ALTER TABLE H_OBSERVACION ADD CONSTRAINT FK_LOCALIDAD FOREIGN KEY (SK_LOCALIDAD) REFERENCES D_LOCALIDAD(SK_LOCALIDAD);
ALTER TABLE H_OBSERVACION ADD CONSTRAINT FK_ZONA FOREIGN KEY (SK_ZONA) REFERENCES D_ZONA(SK_ZONA);
ALTER TABLE H_OBSERVACION ADD CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (SK_DEPARTAMENTO) REFERENCES D_DEPARTAMENTO(SK_DEPARTAMENTO);
ALTER TABLE H_OBSERVACION ADD CONSTRAINT FK_REVISION FOREIGN KEY (SK_REVISION) REFERENCES D_REVISION(SK_REVISION);
ALTER TABLE H_OBSERVACION ADD CONSTRAINT FK_USUARIO FOREIGN KEY (SK_USUARIO) REFERENCES D_USUARIO(SK_USUARIO);
ALTER TABLE H_OBSERVACION ADD CONSTRAINT FK_TIPO_OBSERVACION FOREIGN KEY (SK_TIPO_OBSERVACION) REFERENCES D_TIPO_OBSERVACION(SK_TIPO_OBSERVACION);

--TRANSFORMACION DE DIMENSIONES--
DROP TABLE ODS_D_ZONA;
CREATE TABLE ODS_D_ZONA(
  SK_ZONA INTEGER NOT NULL, 
  ZONA_PK INTEGER NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL);

INSERT INTO ODS_D_ZONA(SK_ZONA, ZONA_PK, NOMBRE)
SELECT SK_ZONA, ZONA_PK, UPPER(TRIM(NOMBRE)) FROM D_ZONA;

DROP TABLE ODS_D_DEPARTAMENTO;
CREATE TABLE ODS_D_DEPARTAMENTO(
  SK_DEPARTAMENTO INTEGER NOT NULL, 
  DEPARTAMENTO_PK INTEGER NOT NULL, 
  NOMBRE VARCHAR(50) NOT NULL);

INSERT INTO ODS_D_DEPARTAMENTO(SK_DEPARTAMENTO, DEPARTAMENTO_PK, NOMBRE)  
SELECT SK_DEPARTAMENTO, DEPARTAMENTO_PK, UPPER(RTRIM(NOMBRE)) FROM D_DEPARTAMENTO;

DROP TABLE ODS_D_LOCALIDAD;
CREATE TABLE ODS_D_LOCALIDAD(
  SK_LOCALIDAD INTEGER NOT NULL,
  LOCALIDAD_PK INTEGER NOT NULL, 
  NOMBRE VARCHAR(50) NOT NULL);
  
CREATE OR REPLACE PROCEDURE P_ODS_D_LOCALIDAD
IS 
BEGIN
  DELETE FROM ODS_D_LOCALIDAD;
  INSERT INTO ODS_D_LOCALIDAD(SK_LOCALIDAD, LOCALIDAD_PK, NOMBRE)
  SELECT SK_LOCALIDAD, LOCALIDAD_PK, UPPER(TRIM(NOMBRE)) FROM D_LOCALIDAD;
  COMMIT;
END P_ODS_D_LOCALIDAD;
EXECUTE P_ODS_D_LOCALIDAD;

DROP TABLE ODS_D_REVISION;
CREATE TABLE ODS_D_REVISION(
  SK_REVISION INTEGER NOT NULL,
  FECHA DATE,
  FIABILIDAD VARCHAR(50) NOT NULL);

CREATE OR REPLACE PROCEDURE P_ODS_D_REVISION
IS 
BEGIN
  DELETE FROM ODS_D_REVISION;
  INSERT INTO ODS_D_REVISION(SK_REVISION, FECHA,FIABILIDAD)
  SELECT SK_REVISION, FECHA, FIABILIDAD FROM D_REVISION;
  COMMIT;
END P_ODS_D_REVISION;
EXECUTE P_ODS_D_REVISION;

DROP TABLE ODS_D_TIPO_OBSERVACION;
CREATE TABLE ODS_D_TIPO_OBSERVACION(
  SK_TIPO_OBSERVACION INTEGER NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  DESCRIPCION VARCHAR(250) NOT NULL);
 
CREATE OR REPLACE PROCEDURE P_ODS_D_TIPO_OBSERVACION
IS 
BEGIN
  DELETE FROM ODS_D_TIPO_OBSERVACION;
  INSERT INTO ODS_D_TIPO_OBSERVACION(SK_TIPO_OBSERVACION, NOMBRE,DESCRIPCION)
  SELECT SK_TIPO_OBSERVACION, NOMBRE, DESCRIPCION FROM D_TIPO_OBSERVACION;
  COMMIT;
END P_ODS_D_TIPO_OBSERVACION;
EXECUTE P_ODS_D_TIPO_OBSERVACION;  

DROP TABLE ODS_D_USUARIO;
CREATE TABLE ODS_D_USUARIO(
  SK_USUARIO INTEGER NOT NULL,
  USUARIO VARCHAR(30) NOT NULL);
  
CREATE OR REPLACE PROCEDURE P_ODS_D_USUARIO
IS 
BEGIN
  DELETE FROM ODS_D_USUARIO;
  INSERT INTO ODS_D_USUARIO(SK_USUARIO, USUARIO)
  SELECT SK_USUARIO, USUARIO FROM D_USUARIO;
  COMMIT;
END P_ODS_D_USUARIO;
EXECUTE P_ODS_D_USUARIO;  

DROP TABLE ODS_H_OBSERVACION;
CREATE TABLE ODS_H_OBSERVACION(
  SK_OBSERVACION INTEGER NOT NULL, 
  SK_DEPARTAMENTO INTEGER NOT NULL, 
  SK_LOCALIDAD INTEGER NOT NULL,
  SK_REVISION INTEGER,
  SK_TIPO_OBSERVACION INTEGER NOT NULL,
  SK_USUARIO INTEGER NOT NULL,
  SK_ZONA INTEGER NOT NULL,
  FECHA DATE);

CREATE OR REPLACE PROCEDURE P_ODS_H_OBSERVACION
IS 
BEGIN
DELETE FROM ODS_H_OBSERVACION;
INSERT INTO ODS_H_OBSERVACION(SK_OBSERVACION, SK_DEPARTAMENTO, SK_LOCALIDAD, SK_REVISION, SK_TIPO_OBSERVACION, SK_USUARIO, SK_ZONA,FECHA)
SELECT SK_OBSERVACION, SK_DEPARTAMENTO, SK_LOCALIDAD, SK_REVISION, SK_TIPO_OBSERVACION, SK_USUARIO, SK_ZONA, FECHA FROM H_OBSERVACION;
COMMIT;
END P_ODS_H_OBSERVACION;
EXECUTE P_ODS_H_OBSERVACION;  

--CARGA DE DATOS--

DROP TABLE DT_DEPARTAMENTO;
CREATE TABLE DT_DEPARTAMENTO(
  SK_DEPARTAMENTO INTEGER NOT NULL, 
  DEPARTAMENTO_PK INTEGER NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL, 
  CONSTRAINT SK_DT_DEPARTAMENTO PRIMARY KEY (SK_DEPARTAMENTO));

CREATE OR REPLACE PROCEDURE P_DT_DEPARTAMENTO
IS
BEGIN
  DELETE FROM DT_DEPARTAMENTO;
  INSERT INTO DT_DEPARTAMENTO(SK_DEPARTAMENTO, DEPARTAMENTO_PK, NOMBRE)
  SELECT SK_DEPARTAMENTO, DEPARTAMENTO_PK, NOMBRE FROM ODS_D_DEPARTAMENTO;
  COMMIT;
END P_DT_DEPARTAMENTO;
EXECUTE P_DT_DEPARTAMENTO;

DROP TABLE DT_LOCALIDAD;
CREATE TABLE DT_LOCALIDAD(
  SK_LOCALIDAD INTEGER NOT NULL, 
  LOCALIDAD_PK INTEGER NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL, 
  CONSTRAINT SK_DT_LOCALIDAD PRIMARY KEY (SK_LOCALIDAD));

CREATE OR REPLACE PROCEDURE P_DT_LOCALIDAD
IS
BEGIN
  DELETE FROM DT_LOCALIDAD;
  INSERT INTO DT_LOCALIDAD(SK_LOCALIDAD, LOCALIDAD_PK, NOMBRE)
  SELECT SK_LOCALIDAD, LOCALIDAD_PK, NOMBRE FROM ODS_D_LOCALIDAD;
  COMMIT;
END P_DT_LOCALIDAD;
EXECUTE P_DT_LOCALIDAD;

DROP TABLE DT_REVISION;
CREATE TABLE DT_REVISION(
  SK_REVISION INTEGER NOT NULL, 
  FECHA DATE,
  FIABILIDAD VARCHAR(50) NOT NULL, 
  CONSTRAINT SK_DT_REVISION PRIMARY KEY (SK_REVISION));

CREATE OR REPLACE PROCEDURE P_DT_REVISION
IS
BEGIN
  DELETE FROM DT_REVISION;
  INSERT INTO DT_REVISION(SK_REVISION, FECHA, FIABILIDAD)
  SELECT SK_REVISION, FECHA, FIABILIDAD FROM ODS_D_REVISION;
  COMMIT;
END P_DT_REVISION;
EXECUTE P_DT_REVISION;

DROP TABLE DT_TIPO_OBSERVACION;
CREATE TABLE DT_TIPO_OBSERVACION(
  SK_TIPO_OBSERVACION INTEGER NOT NULL, 
  NOMBRE VARCHAR(50) NOT NULL,
  DESCRIPCION VARCHAR(250) NOT NULL, 
  CONSTRAINT SK_DT_TIPO_OBSERVACION PRIMARY KEY (SK_TIPO_OBSERVACION));

CREATE OR REPLACE PROCEDURE P_DT_TIPO_OBSERVACION
IS
BEGIN
  DELETE FROM DT_TIPO_OBSERVACION;
  INSERT INTO DT_TIPO_OBSERVACION(SK_TIPO_OBSERVACION, NOMBRE, DESCRIPCION)
  SELECT SK_TIPO_OBSERVACION, NOMBRE, DESCRIPCION FROM ODS_D_TIPO_OBSERVACION;
  COMMIT;
END P_DT_TIPO_OBSERVACION;
EXECUTE P_DT_TIPO_OBSERVACION;

DROP TABLE DT_USUARIO;
CREATE TABLE DT_USUARIO(
  SK_USUARIO INTEGER NOT NULL, 
  USUARIO VARCHAR(30) NOT NULL, 
  CONSTRAINT SK_DT_USUARIO PRIMARY KEY (SK_USUARIO));

CREATE OR REPLACE PROCEDURE P_DT_USUARIO
IS
BEGIN
  DELETE FROM DT_USUARIO;
  INSERT INTO DT_USUARIO(SK_USUARIO,USUARIO)
  SELECT SK_USUARIO, USUARIO FROM ODS_D_USUARIO;
  COMMIT;
END P_DT_USUARIO;
EXECUTE P_DT_USUARIO;

DROP TABLE DT_ZONA;
CREATE TABLE DT_ZONA(
  SK_ZONA INTEGER NOT NULL,
  ZONA_PK INTEGER NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL, 
  CONSTRAINT SK_DT_ZONA PRIMARY KEY (SK_ZONA));

CREATE OR REPLACE PROCEDURE P_DT_ZONA
IS
BEGIN
  DELETE FROM DT_ZONA;
  INSERT INTO DT_ZONA(SK_ZONA,ZONA_PK, NOMBRE)
  SELECT SK_ZONA, ZONA_PK, NOMBRE FROM ODS_D_ZONA;
  COMMIT;
END P_DT_ZONA;
EXECUTE P_DT_ZONA;


DROP TABLE DT_TIEMPO;
CREATE TABLE DT_TIEMPO(
  SK_TIEMPO INTEGER NOT NULL,
  FECHA DATE NOT NULL,
  CONSTRAINT SK_TIEMPO PRIMARY KEY (SK_TIEMPO));

CREATE OR REPLACE PROCEDURE P_DT_TIEMPO  
  IS 
	FECHA_DESDE DATE;  
  FECHA_HASTA DATE; 
    
  BEGIN 
    SELECT MIN(FECHA) 
    INTO FECHA_DESDE
    FROM ODS_H_OBSERVACION; 
    
    SELECT MAX(FECHA)+1
    INTO FECHA_HASTA
    FROM ODS_H_OBSERVACION;
       
  WHILE FECHA_DESDE <= FECHA_HASTA      
    LOOP       
      INSERT INTO DT_TIEMPO           
        (SK_TIEMPO, FECHA)       
      VALUES           
        (TO_NUMBER(TO_CHAR(FECHA_DESDE,'YYYYMMDD')),FECHA_DESDE);       
        FECHA_DESDE := FECHA_DESDE + 1;     
    END LOOP; 
  COMMIT;  
END P_DT_TIEMPO;


DROP TABLE HT_OBSERVACION;
CREATE TABLE HT_OBSERVACION(
  SK_OBSERVACION INTEGER NOT NULL, 
  SK_DEPARTAMENTO INTEGER NOT NULL, 
  SK_LOCALIDAD INTEGER NOT NULL,
  SK_REVISION INTEGER,
  SK_TIPO_OBSERVACION INTEGER NOT NULL,
  SK_USUARIO INTEGER NOT NULL,
  SK_ZONA INTEGER NOT NULL,
  SK_TIEMPO INTEGER NOT NULL,
  CANTIDAD INTEGER NOT NULL
  );
  
  
ALTER TABLE HT_OBSERVACION ADD CONSTRAINT FK_DT_LOCALIDAD FOREIGN KEY (SK_LOCALIDAD) REFERENCES DT_LOCALIDAD(SK_LOCALIDAD);
ALTER TABLE HT_OBSERVACION ADD CONSTRAINT FK_DT_ZONA FOREIGN KEY (SK_ZONA) REFERENCES DT_ZONA(SK_ZONA);
ALTER TABLE HT_OBSERVACION ADD CONSTRAINT FK_DT_DEPARTAMENTO FOREIGN KEY (SK_DEPARTAMENTO) REFERENCES DT_DEPARTAMENTO(SK_DEPARTAMENTO);
ALTER TABLE HT_OBSERVACION ADD CONSTRAINT FK_DT_REVISION FOREIGN KEY (SK_REVISION) REFERENCES DT_REVISION(SK_REVISION);
ALTER TABLE HT_OBSERVACION ADD CONSTRAINT FK_DT_USUARIO FOREIGN KEY (SK_USUARIO) REFERENCES DT_USUARIO(SK_USUARIO);
ALTER TABLE HT_OBSERVACION ADD CONSTRAINT FK_DT_TIPO_OBSERVACION FOREIGN KEY (SK_TIPO_OBSERVACION) REFERENCES DT_TIPO_OBSERVACION(SK_TIPO_OBSERVACION);
ALTER TABLE HT_OBSERVACION ADD CONSTRAINT FK_DT_TIEMPO FOREIGN KEY (SK_TIEMPO) REFERENCES DT_TIEMPO(SK_TIEMPO);

CREATE OR REPLACE PROCEDURE P_HT_OBSERVACION
IS 
BEGIN
DELETE FROM HT_OBSERVACION;
INSERT INTO HT_OBSERVACION(SK_OBSERVACION, SK_DEPARTAMENTO, SK_LOCALIDAD, SK_REVISION, SK_TIPO_OBSERVACION, SK_USUARIO, SK_ZONA,SK_TIEMPO,CANTIDAD)
SELECT SK_OBSERVACION, SK_DEPARTAMENTO, SK_LOCALIDAD, SK_REVISION, SK_TIPO_OBSERVACION, SK_USUARIO, SK_ZONA, 
T.SK_TIEMPO,1 FROM ODS_H_OBSERVACION O JOIN DT_TIEMPO T ON O.FECHA LIKE T.FECHA;
COMMIT;
END P_HT_OBSERVACION;
EXECUTE P_HT_OBSERVACION;  

--CREACION DE VISTAS--
CREATE OR REPLACE VIEW V_OBS_EVOL_MENSUAL_DEP
AS
SELECT D.NOMBRE AS DEPARTAMENTO, COUNT (CANTIDAD) AS CANTIDAD
FROM HT_OBSERVACION O JOIN DT_DEPARTAMENTO D ON O.SK_DEPARTAMENTO = D.SK_DEPARTAMENTO 
GROUP BY D.NOMBRE;
SELECT * FROM V_OBS_EVOL_MENSUAL_DEP ORDER BY 1;

CREATE OR REPLACE VIEW V_OBS_EVOL_MENSUAL_FEN
AS
SELECT T.NOMBRE AS FENOMENO, COUNT (CANTIDAD) AS CANTIDAD
FROM HT_OBSERVACION O JOIN DT_TIPO_OBSERVACION T ON O.SK_TIPO_OBSERVACION = T.SK_TIPO_OBSERVACION
GROUP BY T.NOMBRE;

SELECT * FROM V_OBS_EVOL_MENSUAL_FEN ORDER BY 1;